# typed: false
# frozen_string_literal: true

# Generated by et.rs release automation. Do not edit by hand.
class EtRs < Formula
  desc "Single telemetry-free EternalTerminal binary (Rust port)"
  homepage "https://github.com/minpeter/et.rs"
  version "0.0.11"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.11/et-0.0.11-aarch64-apple-darwin.tar.gz"
      sha256 "acc7a6f64c8cc561ba72385fb0c7ca860d5377764321bc88e513c0c7d6caa7c0"
    end
    on_intel do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.11/et-0.0.11-x86_64-apple-darwin.tar.gz"
      sha256 "1682a45e69bc3f89e5473e7999992b319d8ffecb7aa5898677f29c30f23c7bbd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.11/et-0.0.11-aarch64-unknown-linux-musl.tar.gz"
      sha256 "06694b91342fa4724f39391b657aaa0b27c29280d50f4dddb9ff05ce4b438d80"
    end
    on_intel do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.11/et-0.0.11-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2232cfb4390b79b22f48858b8064d4cd67ead96215d62572ea6378a20b93efe6"
    end
  end

  # Both install `et`, `etserver`, `etterminal`, `htm` and `htmd`.
  conflicts_with "et", because: "et.rs is a drop-in replacement for EternalTerminal"

  def install
    bin.install "et"
    %w[etserver etterminal htm htmd].each do |role|
      bin.install_symlink "et" => role
    end
  end

  test do
    assert_match "et version #{version}", shell_output("#{bin}/et --version")
  end
end
