# typed: false
# frozen_string_literal: true

# Generated by et.rs release automation. Do not edit by hand.
class EtRs < Formula
  desc "Single telemetry-free EternalTerminal binary (Rust port)"
  homepage "https://github.com/minpeter/et.rs"
  version "0.0.21"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.21/et-0.0.21-aarch64-apple-darwin.tar.gz"
      sha256 "434f427e92e4de6895ea70e8fcb75343300c9293d797d309c19c91f70da4f0ab"
    end
    on_intel do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.21/et-0.0.21-x86_64-apple-darwin.tar.gz"
      sha256 "2ea0973f346e471727e1bfdd8207fd418c7186367e7b3ce3989d57af3bc6acb2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.21/et-0.0.21-aarch64-unknown-linux-musl.tar.gz"
      sha256 "f168dabe9f1362cbd5da472647ca5d59bc479ae35f09f12f76bf82275d206e0d"
    end
    on_intel do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.21/et-0.0.21-x86_64-unknown-linux-musl.tar.gz"
      sha256 "28c6a8f12734f986beb31c3a783f1c4bf792e594ae61c643ccfc078a8c9c4be2"
    end
  end

  # Both install `et`, `etserver`, `etterminal`, `htm` and `htmd`.
  conflicts_with "et", because: "et.rs is a drop-in replacement for EternalTerminal"

  def install
    bin.install "et"
    %w[etserver etterminal htm htmd].each do |role|
      bin.install_symlink "et" => role
    end
  end

  test do
    assert_match "et version #{version}", shell_output("#{bin}/et --version")
  end
end
