# typed: false
# frozen_string_literal: true

# Generated by et.rs release automation. Do not edit by hand.
class EtRs < Formula
  desc "Single telemetry-free EternalTerminal binary (Rust port)"
  homepage "https://github.com/minpeter/et.rs"
  version "0.0.22"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.22/et-0.0.22-aarch64-apple-darwin.tar.gz"
      sha256 "452af96bfd4d84b12ebc0e25d92be4de0efa94a028a7e4c9d9e24e75b82e181c"
    end
    on_intel do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.22/et-0.0.22-x86_64-apple-darwin.tar.gz"
      sha256 "01cdb590873fe685789f2462d0b5a8b7d9e1012aa4fb3987e2887952326e5bc0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.22/et-0.0.22-aarch64-unknown-linux-musl.tar.gz"
      sha256 "ba7d2a7023f9740e150135cecead6af7c47d084de5e5ae5ee29c3aa20c6f0e41"
    end
    on_intel do
      url "https://github.com/minpeter/et.rs/releases/download/et@0.0.22/et-0.0.22-x86_64-unknown-linux-musl.tar.gz"
      sha256 "def829a4e18ae13b6aa86f5e736209ad79eec548476917016f24fae8584887d2"
    end
  end

  # Both install `et`, `etserver`, `etterminal`, `htm` and `htmd`.
  conflicts_with "et", because: "et.rs is a drop-in replacement for EternalTerminal"

  def install
    bin.install "et"
    %w[etserver etterminal htm htmd].each do |role|
      bin.install_symlink "et" => role
    end
  end

  test do
    assert_match "et version #{version}", shell_output("#{bin}/et --version")
  end
end
